url: 
  - https://app.zichen.zone/api/acg.php
  - https://api.dujin.org/pic/yuanshen
isopen: true
isMaster: false
getcd: 0
chcd: 60
maxnum: 10
reg: 二元图
blackgroup:
  - 123456
  - 456789
  - 123456789
whitegroup: