url1: https://image.anosu.top/pixiv/direct?r18=1
url2: https://image.anosu.top/pixiv/direct?r18=1&keyword=genshinimpact
url3: http://www.ashking.ltd/18.php
url4: https://www.acy.moe/api/r18
url5: https://moe.jitsu.top/api/?sort=r18&size=small&type=302
isopen: false
isMaster: false
getcd: 0
chcd: 0
maxnum: 10