url1: https://tuapi.eees.cc/api.php?category=meinv&type=302
url2: https://cdn.seovx.com/?mom=302
url3: http://ovooa.com/API/meinv/api.php?type=image
url4: http://api.btstu.cn/sjbz/
url5: http://tfapi.top/API/nypic.php
url6: https://cdn.seovx.com/ha?mom=302
isopen: false
isMaster: false
getcd: 0
chcd: 0
maxnum: 10