url: https://xiaobapi.top/api/xb/api/pixiv_r18.php
token: 替换成你的账号
password: 替换成你的密码
isopen: true
isMaster: false
getcd: 0
chcd: 60
maxnum: 10
reg: 铯(p|P)图
blackgroup:
  - 123456
  - 456789
  - 123456789
whitegroup: